<a href="https://colab.research.google.com/github/jaafar19/NLP/blob/main/TextRankTextSummarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import textwrap
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer, PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer

nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [2]:
!wget -nc https://lazyprogrammer.me/course_files/nlp/bbc_text_cls.csv

--2025-04-03 10:04:29--  https://lazyprogrammer.me/course_files/nlp/bbc_text_cls.csv
Resolving lazyprogrammer.me (lazyprogrammer.me)... 172.67.213.166, 104.21.23.210, 2606:4700:3030::ac43:d5a6, ...
Connecting to lazyprogrammer.me (lazyprogrammer.me)|172.67.213.166|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5085081 (4.8M) [text/csv]
Saving to: ‘bbc_text_cls.csv’

bbc_text_cls.csv    100%[===================>]   4.85M  --.-KB/s    in 0.08s   

2025-04-03 10:04:29 (57.4 MB/s) - ‘bbc_text_cls.csv’ saved [5085081/5085081]



In [3]:
df = pd.read_csv('bbc_text_cls.csv')

In [6]:
doc = df[df.labels == 'business']['text'].sample(random_state=42)
doc

480    Christmas sales worst since 1981\n\nUK retail ...
Name: text, dtype: object

In [7]:
def wrap(x):
  return textwrap.fill(x, replace_whitespace=False, fix_sentence_endings=True)

In [8]:
print (wrap(doc.iloc[0]))

Christmas sales worst since 1981

UK retail sales fell in December,
failing to meet expectations and making it by some counts the worst
Christmas since 1981.

Retail sales dropped by 1% on the month in
December, after a 0.6% rise in November, the Office for National
Statistics (ONS) said.  The ONS revised the annual 2004 rate of growth
down from the 5.9% estimated in November to 3.2%. A number of
retailers have already reported poor figures for December.  Clothing
retailers and non-specialist stores were the worst hit with only
internet retailers showing any significant growth, according to the
ONS.

The last time retailers endured a tougher Christmas was 23 years
previously, when sales plunged 1.7%.

The ONS echoed an earlier
caution from Bank of England governor Mervyn King not to read too much
into the poor December figures.  Some analysts put a positive gloss on
the figures, pointing out that the non-seasonally-adjusted figures
showed a performance comparable with 2003. The Novembe

In [9]:
sents = nltk.sent_tokenize(doc.iloc[0].split("\n", 1)[1])

In [10]:
featurizer = TfidfVectorizer(stop_words=stopwords.words('english'), norm='l1')

In [11]:
x = featurizer.fit_transform(sents)

In [12]:
from sklearn.metrics.pairwise import cosine_similarity

S= cosine_similarity(x)

In [15]:
S

array([[1.        , 0.12277059, 0.        , 0.05996659, 0.05227621,
        0.09521169, 0.03957788, 0.        , 0.0353568 , 0.03154382,
        0.        , 0.        , 0.15640655, 0.03602562, 0.03219522,
        0.09434004, 0.        ],
       [0.12277059, 1.        , 0.14622599, 0.06787268, 0.04909301,
        0.04940377, 0.09771336, 0.        , 0.09699398, 0.03570261,
        0.        , 0.05146693, 0.0438789 , 0.04077529, 0.08658211,
        0.10677797, 0.        ],
       [0.        , 0.14622599, 1.        , 0.        , 0.14160853,
        0.        , 0.06110337, 0.        , 0.06578936, 0.        ,
        0.        , 0.        , 0.10444293, 0.        , 0.        ,
        0.        , 0.        ],
       [0.05996659, 0.06787268, 0.        , 1.        , 0.0996264 ,
        0.05921692, 0.20528561, 0.09620589, 0.05587403, 0.09969683,
        0.0638979 , 0.        , 0.        , 0.14962341, 0.13525503,
        0.04210404, 0.        ],
       [0.05227621, 0.04909301, 0.14160853, 0.099626

In [16]:
len(sents)

17

In [17]:
S /= S.sum(axis=1, keepdims=True)

In [18]:
S

array([[0.56958279, 0.06992802, 0.        , 0.03415594, 0.02977563,
        0.05423094, 0.02254288, 0.        , 0.02013862, 0.01796682,
        0.        , 0.        , 0.08908648, 0.02051957, 0.01833784,
        0.05373446, 0.        ],
       [0.06153121, 0.50118852, 0.07328679, 0.03401701, 0.02460485,
        0.0247606 , 0.04897281, 0.        , 0.04861227, 0.01789374,
        0.        , 0.02579464, 0.0219916 , 0.02043611, 0.04339396,
        0.05351589, 0.        ],
       [0.        , 0.09625386, 0.6582541 , 0.        , 0.09321439,
        0.        , 0.04022154, 0.        , 0.04330612, 0.        ,
        0.        , 0.        , 0.06874999, 0.        , 0.        ,
        0.        , 0.        ],
       [0.02809233, 0.03179606, 0.        , 0.46846628, 0.04667161,
        0.02774113, 0.09616939, 0.04506922, 0.0261751 , 0.04670461,
        0.02993401, 0.        , 0.        , 0.07009352, 0.06336242,
        0.01972432, 0.        ],
       [0.0293286 , 0.02754272, 0.07944685, 0.055893

In [20]:
S[0].sum()

np.float64(1.0)

In [21]:
U = np.ones_like(S) / len(S)

In [22]:
U

array([[0.05882353, 0.05882353, 0.05882353, 0.05882353, 0.05882353,
        0.05882353, 0.05882353, 0.05882353, 0.05882353, 0.05882353,
        0.05882353, 0.05882353, 0.05882353, 0.05882353, 0.05882353,
        0.05882353, 0.05882353],
       [0.05882353, 0.05882353, 0.05882353, 0.05882353, 0.05882353,
        0.05882353, 0.05882353, 0.05882353, 0.05882353, 0.05882353,
        0.05882353, 0.05882353, 0.05882353, 0.05882353, 0.05882353,
        0.05882353, 0.05882353],
       [0.05882353, 0.05882353, 0.05882353, 0.05882353, 0.05882353,
        0.05882353, 0.05882353, 0.05882353, 0.05882353, 0.05882353,
        0.05882353, 0.05882353, 0.05882353, 0.05882353, 0.05882353,
        0.05882353, 0.05882353],
       [0.05882353, 0.05882353, 0.05882353, 0.05882353, 0.05882353,
        0.05882353, 0.05882353, 0.05882353, 0.05882353, 0.05882353,
        0.05882353, 0.05882353, 0.05882353, 0.05882353, 0.05882353,
        0.05882353, 0.05882353],
       [0.05882353, 0.05882353, 0.05882353, 0.058823

In [23]:
factor = 0.15
S = (1 - factor) * S + factor * U

In [25]:
S[0].sum()

np.float64(0.9999999999999999)

In [26]:
eigenValues, eigenVectors = np.linalg.eig(S.T)

In [27]:
eigenValues

array([1.        , 0.24245466, 0.72108199, 0.67644122, 0.34790129,
       0.34417302, 0.3866884 , 0.40333562, 0.41608572, 0.44238593,
       0.63909999, 0.62556792, 0.58922572, 0.57452382, 0.48511399,
       0.51329157, 0.52975372])

In [28]:
eigenVectors[:,0]

array([-0.24206557, -0.27051337, -0.2213806 , -0.28613638, -0.25065894,
       -0.2499217 , -0.279622  , -0.21515455, -0.2226665 , -0.22745415,
       -0.2059112 , -0.20959727, -0.23526242, -0.24203809, -0.23663025,
       -0.2940483 , -0.20865607])

In [29]:
eigenVectors[:,0].dot(S)

array([-0.24206557, -0.27051337, -0.2213806 , -0.28613638, -0.25065894,
       -0.2499217 , -0.279622  , -0.21515455, -0.2226665 , -0.22745415,
       -0.2059112 , -0.20959727, -0.23526242, -0.24203809, -0.23663025,
       -0.2940483 , -0.20865607])

In [30]:
eigenVectors[:,0] / eigenVectors[:,0].sum()

array([0.05907327, 0.06601563, 0.05402535, 0.06982824, 0.06117038,
       0.06099047, 0.06823848, 0.05250595, 0.05433915, 0.05550753,
       0.05025022, 0.05114976, 0.05741304, 0.05906657, 0.05774684,
       0.07175905, 0.05092007])

In [31]:
limiting_dist = np.ones(len(S)) / len(S)
threshold = 1e-8
delta = float('inf')
iters = 0
while delta > threshold:
  iters += 1
  p = limiting_dist.dot(S)
  delta = np.abs(p - limiting_dist).sum()
  limiting_dist = p
print(iters)

41


In [32]:
limiting_dist

array([0.05907327, 0.06601563, 0.05402534, 0.06982824, 0.06117038,
       0.06099047, 0.06823848, 0.05250595, 0.05433915, 0.05550753,
       0.05025022, 0.05114977, 0.05741304, 0.05906657, 0.05774685,
       0.07175905, 0.05092008])

In [33]:
limiting_dist.sum()

np.float64(0.9999999999999981)

In [35]:
np.abs(eigenVectors[:,0]/eigenVectors[:,0].sum() - limiting_dist).sum()

np.float64(1.9964739160494016e-08)

In [36]:
scores = limiting_dist

In [37]:
sort_idx = np.argsort(-scores)

In [38]:
print('Generated summary:')
for i in sort_idx[:5]:
  print(wrap("%.2f: %s" % (scores[i]*100, sents[i])))

Generated summary:
7.18: "The retail sales figures are very weak, but as Bank of England
governor Mervyn King indicated last night, you don't really get an
accurate impression of Christmas trading until about Easter," said Mr
Shaw.
6.98: A number of retailers have already reported poor figures for
December.
6.82: The ONS echoed an earlier caution from Bank of England governor
Mervyn King not to read too much into the poor December figures.
6.60: Retail sales dropped by 1% on the month in December, after a
0.6% rise in November, the Office for National Statistics (ONS) said.
6.12: Clothing retailers and non-specialist stores were the worst hit
with only internet retailers showing any significant growth, according
to the ONS.


In [40]:
doc.iloc[0].split('\n',1)[0]

'Christmas sales worst since 1981'

In [44]:
def summarize(text, factor,sentences):
  sents = nltk.sent_tokenize(text)
  featurizer = TfidfVectorizer(stop_words=stopwords.words('english'), norm='l1')
  x = featurizer.fit_transform(sents)
  S = cosine_similarity(x)
  S /= S.sum(axis=1, keepdims=True)
  U = np.ones_like(S) / len(S)
  S = (1 - factor) * S + factor * U
  eigenValues, eigenVectors = np.linalg.eig(S.T)
  limiting_dist = np.ones(len(S)) / len(S)
  threshold = 1e-8
  delta = float('inf')
  iters = 0
  while delta > threshold:
    iters += 1
    p = limiting_dist.dot(S)
    delta = np.abs(p - limiting_dist).sum()
    limiting_dist = p
  scores = limiting_dist
  sort_idx = np.argsort(-scores)
  print('Generated summary:')
  for i in sort_idx[:sentences]:
    print(wrap("%.2f: %s" % (scores[i]*100, sents[i])))


In [45]:
a="The change in the commodity price is the key basis of market transactions and economic management, so it is necessary to make an accurate prediction of the dynamic commodity price. \n However, due to the influences of various hidden factors, the commodity price usually varies frequently and fluctuates violently with obvious nonlinear characteristics. \nTherefore, it is difficult to obtain accurate and robust prediction results only using the historical data of the price itself. \nTo this end, this paper proposes a hybrid multi-factor price forecasting method based on factor selection and fusion with the CNN-LSTM and XGBoost network. Firstly, after we collect the data we calculated using some analytical indicator (RSA, CMF, EMA, ROC, DPO, …), secondly we apply DC framework and calculate DC parameter like aTmv, OSVOS and BM, and after extracting the features we preprocessing the tasks. \nFinally, we start training by trying the algorithm and put hyper¬-parameter and data by testing and evaluation.\nNow, after finishing evaluation we can conclude the advantage of using XGBoost is faster than CNN-LSTM in training with big dataset especially when we take a look at accuracy for all datasets, we have a higher and better accuracy with large number of transactions for XGBoost.\nIn our future work, we will work the model with another algorithm with more analytical indicator to get perfect accuracy and more precisely.\nSo, it is a promising multi-factor forecasting method and can be widely used in other fields. \nConsidering that different exogenous variables have different influences on prices, how to effectively use this characteristic to obtain more accurate prediction results is a direction that will be worthy of more research in the future."

In [47]:
summarize(a,0.15,2)

Generated summary:
11.20: Therefore, it is difficult to obtain accurate and robust
prediction results only using the historical data of the price itself.
10.96: To this end, this paper proposes a hybrid multi-factor price
forecasting method based on factor selection and fusion with the CNN-
LSTM and XGBoost network.
